using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlightControlWeb.Flight
{
    public class IDGenerator : IIDGenerator
    {
        private readonly string prefix;


        /// <summary>
        /// A constructor.
        /// </summary>
        /// <param name="prefix"> A prefix for the ids generated by the generator. </param>
        public IDGenerator(string prefix)
        {
            this.prefix = prefix;
        }


        /// <summary>
        /// Generate an id.
        /// The id is based on the prefix.
        /// </summary>
        /// <returns> The generated id. </returns>
        public string GenerateID()
        {
            return prefix + (new Random()).Next();
        }
    }
}
